import type { Metadata } from 'next';
import NextTopLoader from 'nextjs-toploader';
import { fontVariables } from '@/lib/font';
import { cn } from '@/lib/utils';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'overflow-hidden overscroll-none font-sans antialiased',
          fontVariables
        )}
      >
        <NextTopLoader showSpinner={false} color='var(--primary)' />
        {children}
      </body>
    </html>
  );
}
